title: Streamdata Gallery
url: bank-of-scotland.api.streamdata.gallery
tag: Bank of Scotland
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery-organizations
github_repo: bank-of-scotland
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
